# Dockerfile.frontend
FROM node:18

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps && npm install -g vite

COPY frontend/ .

EXPOSE 3000

CMD ["vite", "preview", "--host", "0.0.0.0", "--port", "3000"]

