FROM node:18

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps && npm install -g vite

COPY frontend/ .

EXPOSE 3000

CMD ["npm", "run", "preview", "--", "--port", "3000", "--host"]
