version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: frontend
    container_name: wanderlust-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: backend
    container_name: wanderlust-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    command: ["npm", "start"]
