FROM node:18

# Set working directory inside container
WORKDIR /app

# Copy backend dependencies and install
COPY backend/package*.json ./
RUN npm install --legacy-peer-deps

# Copy all backend files
COPY backend/ .

# Open the port your backend listens on
EXPOSE 8000

# Start the server using node
CMD ["node", "server.js"]

